# src/main/resources/config.properties
mongodb.connectionString=mongodb+srv://brinyawira24:vvSUycswAduhDlND@cluster0.14pqqtu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
mongodb.databaseName=Quiz_Game
mongodb.username=brinyawira24
mongodb.password=vvSUycswAduhDlND